layout_spectrum: 0.5342683587223291
typography_spectrum: 0.8320444838609546
color:
  brandColors:
    - '#000000'
    - '#404040'
    - '#808080'
    - '#BFBFBF'
    - '#FFFFFF'
  brandStrength: 0.6704171900637448
  lightness: 0.7240145246032625
  saturation: 0.1619490112643689
  rhythmicContrast: 0.004954356234520674
coverPrefs:
  filter: false
opengraph:
  image: null
  type: null
  appId: null
analytics:
  google: UA-74437051-1
  facebook: null
  twitter: null
name: chaos
cta:
  domain: null
  bucket: null
  version: null
favicon: null
title: Videos Chaos
description: ''
purpose: []
