name: chaos
favicon: null
layout_spectrum: 0.48266
typography_spectrum: 0.1875
title: Videos Chaos
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: UA-74437051-1
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#c1d2d2'
    - '#dbe5e5'
    - '#d3dfdf'
    - '#cddbdb'
    - '#e3ebeb'
  brandStrength: 0.6023020977154374
  lightness: 0.7541532595641911
  saturation: 0.7580128824338317
  rhythmicContrast: 0.34280004422180355
purpose: []
