typography_spectrum: 0.9234878628049046
color:
  brandColors:
    - '#FFFFFF'
    - '#DAD7D2'
    - '#6B5363'
    - '#6C87BC'
    - '#E58D65'
  brandStrength: 0.4316094310488552
  lightness: 0.9091900386847556
  saturation: 0.628500266931951
  rhythmicContrast: 0.0016853257548063993
opengraph:
  image: null
  type: null
  appId: null
layout_spectrum: 0.5022672980558127
analytics:
  google: UA-74437051-1
  facebook: null
  twitter: null
name: chaos
cta:
  domain: null
  bucket: null
  version: null
favicon: null
title: Videos Chaos
coverPrefs:
  filter: false
description: ''
purpose: []
