typography_spectrum: 0.5541159727144986
color:
  brandColors:
    - '#595241'
    - '#B8AE9C'
    - '#FFFFFF'
    - '#ACCFCC'
    - '#8A0917'
  brandStrength: 0.8379875367973
  lightness: 0.9406890014652163
  saturation: 0.579653512686491
  rhythmicContrast: 0.3641461902298033
opengraph:
  image: null
  type: null
  appId: null
layout_spectrum: 0.4435287010855973
analytics:
  google: UA-74437051-1
  facebook: null
  twitter: null
name: chaos
cta:
  domain: null
  bucket: null
  version: null
favicon: null
title: Videos Chaos
coverPrefs:
  filter: false
description: TVidEos
purpose: []
