name: chaos
favicon: null
layout_spectrum: 0.99133
typography_spectrum: 0.1875
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: UA-74437051-1
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#feebcb'
    - '#1d2437'
    - '#9a8298'
    - '#646077'
    - '#404354'
  brandStrength: 0.6023020977154374
  lightness: 0.7541532595641911
  saturation: 0.7580128824338317
  rhythmicContrast: 0.34280004422180355
purpose: []
