name: chaos
favicon: null
layout_spectrum: 0.4435287010855973
typography_spectrum: 0.5541159727144986
title: Videos Chaos
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: UA-74437051-1
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#595241'
    - '#B8AE9C'
    - '#FFFFFF'
    - '#ACCFCC'
    - '#8A0917'
  brandStrength: 0.8379875367973
  lightness: 0.9406890014652163
  saturation: 0.579653512686491
  rhythmicContrast: 0.3641461902298033
purpose: []
coverPrefs:
  filter: false
