name: chaos
favicon: null
layout_spectrum: 0.48266
typography_spectrum: 0.1875
title: Videos Chaos
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: UA-74437051-1
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffea37'
    - '#030303'
    - '#b17f36'
    - '#c9b8a8'
    - '#614a3a'
  brandStrength: 0.6023020977154374
  lightness: 0.7541532595641911
  saturation: 0.7580128824338317
  rhythmicContrast: 0.34280004422180355
purpose: []
